version: "3.8"
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    working_dir: /mlflow
    environment:
      # AWS credentials pour S3
      AWS_ACCESS_KEY_ID: ASIA2JBGQTPQWSHENLJO
      AWS_SECRET_ACCESS_KEY: rjqGHubMjIPVza/eH+0NhISjS+vzzNYXggr6IQ40
      AWS_DEFAULT_REGION: us-east-1 
      AWS_SESSION_TOKEN: 
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5001
      --backend-store-uri sqlite:///mlflow.db
      --artifacts-destination /mlflow/artifacts
    ports:
      - "5001:5001"
    volumes:
      - mlflowdata:/mlflow
volumes:
  mlflowdata: {}
