name: Deploy Churn Service

on:
  push:
    branches: [ "main" ]
    # Changement 1 : On ne déclenche que si ce dossier change
    paths:
      - 'flask_prediction_churn/**'
      - '.github/workflows/deploy.yml'

env:
  # On donne un nom spécifique à cette image
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/churn-service:latest
  # Le nom du dossier exact
  SERVICE_PATH: ./flask_prediction_churn

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Changement 2 : On construit depuis le sous-dossier
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        # C'est ici qu'on dit "entre dans le dossier avant de build"
        context: ${{ env.SERVICE_PATH }}
        push: true
        tags: ${{ env.IMAGE_NAME }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Login
          echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Arrêter uniquement le service de churn
          docker stop churn_service || true
          docker rm churn_service || true
          
          # Pull la nouvelle image
          docker pull ${{ env.IMAGE_NAME }}
          
          # Lancer (Port 5000)
          # Note: Si vous avez d'autres services, assurez-vous que le port 5000 est libre
          docker run -d -p 5000:5000 --name churn_service ${{ env.IMAGE_NAME }}